# Data selection parameters
data:
  reference_date: null # Date to process (e.g., "2017-06-15"). It can be ovewritten by the --date in the command-line

  subset_name: null # Subset name (e.g., "2025" or a custom string e.g., "2024_18mp") used to construct file paths and output directories. By default the year extracted from reference_date is used as subset_name, but it can be overwritten by setting this parameter.
  camera_name: "PPCX_Tele" # Name of the camera ("PPCX_Tele", "PPCX_Wide").

  base_output_dir: "output_anomaly/${data.subset_name}_${data.camera_name}" # Output directory base path. The actual output of each run will be saved in a subdirectory of this path, determined by run_output_subdir.
  run_output_subdir: "${data.reference_date}" # Subdirectory name for the current run's output (e.g., "2025-01-08"). This will be created inside base_output_dir. If null, the base_output_dir will be used directly without creating a subfolder.

  # Data Source Configuration
  dic_file_path: null    # Path to input DIC map file (e.g. NetCDF)
  search_dir: "/mnt/irpinas/planpincieux/data/${data.subset_name}/correlation/day_dic_ensemble_netcdf" # Directory to search for input files if source is "file".
  search_pattern: 'day_dic_(?P<slave>\d{4}-\d{2}-\d{2})_(?P<master>\d{4}-\d{2}-\d{2})_dt(?P<dt>\d+)_.*\.nc' # Regular expression pattern to extract slave date, master date, and time difference from filenames. 
  # The pattern should include named groups for the relevant metadata (master, slave, dt). For example:
  #   'day_dic_(?P<slave>\d{4}-\d{2}-\d{2})_(?P<master>\d{4}-\d{2}-\d{2})_dt(?P<dt>\d+)_.*\.nc' match filename like: "day_dic_2025-01-08_2025-01-01_dt7_ensemble2.nc".
  image_dir: "/mnt/irpinas/planpincieux/data/${data.subset_name}/coregistration/coregistered"
  sectors_dir: "output_domains/${data.subset_name}_${data.camera_name}/kinematic_sectors_geojson" # Directory containing sector definitions (e.g., shapefiles or GeoJSON files). The code will look for a file named "sectors_${camera_name}.shp" or "sectors_${camera_name}.geojson" in this directory.

  dt_min: 0  # Minimum time difference between images in hours. Used both for files and database sources.
  dt_max: 30  # Maximum time difference between images in hours. Used both for files and database sources.

# Data preprocessing parameters
preprocessing:
  mean_global_mad_threshold: 3.0  # Minimum global MAD (mean of the MAD on the DIC map) threshold. DIC maps with mean MAD below this threshold will be discarded. Set to None to disable global MAD filtering. 
  min_ensemble_size: 2  # Minimum number of DIC maps (ensembles) required for a given date to be included in the analysis. Set to None to disable ensemble size filtering.
  max_point_mad: 3 # Maximum MAD threshold for filtering. Points with MAD above this value will be removed. Set to None to disable MAD filtering.
  filter_kwargs:
    min_velocity: 1.5  # Minimum velocity threshold (units depend on input data)

anomaly_detection:
  target_sector: "A" # Sector to analyze for anomalies (e.g., "A")
  sector_buffer: 100.0 # Buffer distance in meters to expand sector polygons for data selection. This can help include points near the sector boundaries that may be relevant for anomaly detection.

  variables_names: ["V_long", "V_trans"] # or ["V_long", "V_trans"] ["V"] 
  # feature_weights: [0.8, 0.2]  # e.g., [1.0] # Weights for each feature in variables_names. Used only if multiple features are used.

  prior_assignment_method: "velocity+y_coord" # Method to assign priors for anomaly probability. Options: "velocity", "y_coord", "kmeans", or combinations like "velocity+y_coord". This will influence the initial p(anomaly) for each point in the MCMC sampling.

  prior_anomaly_probability_limits: [0.1, 0.9] # Bounds for p(anomaly).
  # The actual p(anomaly) for each point will be assigned based on the chosen method(s) and will lie within these bounds. These values do not have to sum to 1 with p(not anomaly) as the probability of not being an anomaly will be 1 - p(anomaly).


  # MCMC sampling parameters for anomaly detection.
  model_options:
    mu_params:
      mu: [0, 2]
      sigma: [0.5, 1]
    sigma_params:
      sigma: [1, 1]

  sample_options:
    target_accept: 0.99
    draws: 3000
    tune: 2000
    chains: 4

  # mrf_options: # MRF settings specific for anomaly detection (can be more aggressive to capture small anomalous features)
  #   n_neighbors: 6
  #   length_scale: 10
  #   beta: 5.0
  #   n_iter: 10
  
  # second_pass_sample_args:
  #   draws: 1000
  #   tune: 500
  #   chains: 4

  force_cpu: True # Whether to force CPU sampling even if GPU is available

plotting:
  default_discrete_cmap: "tab10"  # Colormap for discrete sector colors when not specified
  default_continuous_cmap: "OrRd"  # Colormap for continuous data plotting (e.g., velocity)
  quiver:
    cmap: "OrRd"
    vmin: 0
    vmax: 15
